#Spring datasource
spring:
  application:
    name: Employee Management System App
  datasource:
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/ad_70cb8bbbc161670?user=b8fa28d956cce9&password=3760de5a
    username: b8fa28d956cce9
    password: 3760de5a
    platform: mysql
#Hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
  